export { compressByType, detectContentType, type ContentType, type CompressOptions, type DetectionResult } from "./router"
export { compressJson } from "./json"
export { compressLog } from "./log"
export { compressSearch } from "./search"
export { extractHtml } from "./html"
export { compressConfig } from "./config"
export { compressCode } from "./code"
export { compressCsv } from "./csv"

export * as Compression from "."
